# Generated by Django 4.2.4 on 2024-03-04 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=11, null=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField(max_length=10)),
                ('description', models.TextField(null=True)),
                ('stock', models.IntegerField(default=10, max_length=10)),
                ('image_path', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SavedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(max_length=10, null=True)),
                ('is_wishlist', models.BooleanField(default=False)),
                ('is_cart', models.BooleanField(default=False)),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='furnitureApi.furniture')),
            ],
        ),
    ]
